# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-09 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('shortinfo', models.CharField(max_length=30, verbose_name='文章简介')),
                ('info', models.TextField(verbose_name='文章内容')),
                ('location', models.CharField(max_length=10, verbose_name='地理位置')),
                ('image', models.ImageField(upload_to='introduction/', verbose_name='游记图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('see_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_show', models.BooleanField(default=True, verbose_name='显示')),
            ],
        ),
        migrations.CreateModel(
            name='IntroductionKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=50, verbose_name='文章关键字列表')),
                ('titleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.IntroductionInfo')),
            ],
        ),
    ]
