# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionmessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
