# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_introductioninfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductionkeyword',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
    ]
